name: check Python formatting

on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    name: check Python formatting
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install
        run: pip install black isort

      - name: Run isort
        run: isort --check-only --quiet python/ tests/

      - name: Run black
        run: black --check python/ tests/
